// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB63S_qj0Hi_D1cQC1LIFj0hRdhmsAJdak',
    appId: '1:1042854083795:web:4ca4e3197c65e112f82826',
    messagingSenderId: '1042854083795',
    projectId: 'automiot',
    authDomain: 'automiot.firebaseapp.com',
    storageBucket: 'automiot.appspot.com',
    measurementId: 'G-Z6LZFVGS0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiM3Lnwht4WA0ZbUmV23XYu16RcXZdpzk',
    appId: '1:1042854083795:android:9f1e79230fb1d5c1f82826',
    messagingSenderId: '1042854083795',
    projectId: 'automiot',
    storageBucket: 'automiot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiQ2Y-BZ5ZxPbHhK0tfnAbyozj8HXGrjM',
    appId: '1:1042854083795:ios:188a5bb5e053e6b7f82826',
    messagingSenderId: '1042854083795',
    projectId: 'automiot',
    storageBucket: 'automiot.appspot.com',
    iosClientId: '1042854083795-03dumm03lh2rjtdgv322me6obi70pg1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.automIOt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiQ2Y-BZ5ZxPbHhK0tfnAbyozj8HXGrjM',
    appId: '1:1042854083795:ios:188a5bb5e053e6b7f82826',
    messagingSenderId: '1042854083795',
    projectId: 'automiot',
    storageBucket: 'automiot.appspot.com',
    iosClientId: '1042854083795-03dumm03lh2rjtdgv322me6obi70pg1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.automIOt',
  );
}
